pages/urls.py
from django.urls import path
from .views import index

app_name = 'pages'
urlpatterns = [
    path('', index, name="index")
]

plx_scraper/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('scrape/', include('scrape.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scrape/urls.py
from django.urls import path
from scrape.views import *

app_name = 'scrape'
urlpatterns = [
    path('', scrape, name='scrape'),
    path('change_path/<int:path_id>/', change_path, name='change_path'),
    path('add_files', add_files, name="add_files"),
    path('add_all_files', add_all_files, name="add_all_files"),
]

pages/models.py
from django.db import models

# Create your models here.

scrape/models.py
from django.db import models



class Path(models.Model):
    path = models.CharField(max_length=200, default="M:/Uklady/PLX")

    def __str__(self):
        return self.path


class Files(models.Model):
    path = models.CharField(max_length=200, default="path")
    column_one = models.CharField(max_length=50, default="PLX")
    column_two = models.CharField(max_length=50, default="PLX_FGK")
    file_name = models.CharField(max_length=50, null=True, blank=True)
    column_three = models.CharField(max_length=50, default="N")
    column_four = models.CharField(max_length=50, default="1")

    def __str__(self):
        return "Name: " + self.file_name
    

scrape/forms.py
from django import forms
from .models import Path


# Create a form for edit path
class PathModelForm(forms.ModelForm):
    path = forms.CharField(widget=forms.TextInput())
    
    class Meta:
        model = Path
        fields = ['path']

pages/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'pages/index.html')

scrape/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from .models import Files, Path
from django.urls import reverse
from .forms import PathModelForm
from django.contrib import messages
from django.template.loader import render_to_string

import os

def scrape(request):

    # Path value
    path = Path.objects.filter().first()
    
    # First 15 files values
    files = Files.objects.all()[:15]
    
    # All files values 
    all_files = Files.objects.all()
    
    # Count all files
    count_files = Files.objects.all().count()
    
    # Search data from files table
    query = request.GET.get("q")

    if query:
        if "%" in query:
            # Change a query "%" to ".*" regex
            query = query.replace("%", ".*")
            files = all_files.filter(file_name__iregex=query)[:80]
            query = query.replace(".*", "%")
        elif "%" not in query:
            files = all_files.filter(file_name__icontains=query)[:80]
        else:
            files = all_files.all()[:70]
            

    context = {
        'files': files,
        'path': path,
        'query': query,
        'count_files': count_files
    }
    
    if request.is_ajax():

        html = render_to_string(
            template_name="scrape/results-partial.html", context={"files": files}
        )
        data_dict = {"html_from_view": html}
        return JsonResponse(data=data_dict, safe=False)

    return render(request, "scrape/list.html", context)


# Add new name files from directory(path)
def add_files(request):
    path = Path.objects.filter().first()
    choice = str(request.POST['choice']).upper()
    if os.path.exists(str(path)):
        path_list = os.listdir(str(path))
        for file in path_list:
            if choice in file.upper():
                file = os.path.splitext(file)[0]
                del_file = Files.objects.filter(file_name=file)
                if del_file:
                    continue
                files = Files(file_name=file, path=path)
                files.save()
        if not any(choice in file.upper() for file in path_list):
            messages.info(request, 'None match of this phrase')
            return redirect("/scrape")
        messages.success(request, 'The database has been updated')
        return redirect('/scrape')
    else:
        messages.info(request, 'The directory doesnt exists. Change the direcotry path!')
        return redirect('/scrape')


# Add all files from directory(path)
def add_all_files(request):
    path = Path.objects.filter().first()
    if os.path.exists(str(path)):
        path_list = os.listdir(str(path))
        for file in path_list:
            file = os.path.splitext(file)[0]
            del_file = Files.objects.filter(file_name=file)
            if del_file:
                continue
            files = Files(file_name=file, path=path)
            files.save()
        messages.success(request, 'The database has been updated')
        return redirect('/scrape')
    else:
        messages.info(request, 'The directory doesnt exists. Change the direcotry path!')
        return redirect('/scrape')


# Change the path
def change_path(request, path_id=None):
    path = Path.objects.get(id=path_id)
    form = PathModelForm(request.POST or None, instance=path)

    if form.is_valid():
        form.save()
        messages.success(request, 'The path has been updated')
        return redirect('/scrape')
    
    context = {
        "form": form
    }

    return render(request, "scrape/change_path.html", context)

pages/templates/pages/index.html
{% extends "base.html" %}
{% block content %}
<style>

.circlearancione {
    background-color: #c80041;
    border-color: white;
    border-radius: 50%;
    border-width: 5px;
    height: 140px;
    width: 140px;
    line-height: 150px;
    margin-left: 150px;
    margin-top: 150px;
}

span {
    margin-left: 150px;
    font-size: 150px;
    font-weight: bold;
    color: #555f5f;
    text-align: center;
    font-family: 'Poppins', sans-serif;
}

</style>

    <div class="circlearancione"><span>LOGO</span></div>

    <!-- <div class="col-sm-9 col-md-7 col-lg-5 mx-auto"> -->
        <!-- <div class="card card-signin my-5"> -->
          <!-- <div class="card-body"> -->
            <!-- <h5 class="card-title text-center">Zaloguj się</h5> -->
            <!-- <form class="form-signin"> -->
              <!-- <div class="form-label-group"> -->
                <!-- <hr> -->
                <!-- <label for="inputEmail">Numer SAP:</label> -->
                <!-- <input type="email" id="inputEmail" class="form-control" placeholder="Podaj nr SAP" required autofocus> -->
              <!-- </div> -->

              <!-- <div class="form-label-group"> -->
                <!-- <hr> -->
                <!-- <label for="inputPassword">Hasło:</label> -->
                <!-- <input type="password" id="inputPassword" class="form-control" placeholder="Podaj hasło" required> -->
              <!-- </div> -->
              <!-- <div class="custom-control custom-checkbox mb-3"> -->
                <!-- <hr> -->
                <!-- <input type="checkbox" class="custom-control-input" id="customCheck1"> -->
              <!-- </div> -->
              <!-- <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Zaloguj się</button> -->
              <!-- <hr class="my-4"> -->
            <!-- </form> -->
          <!-- </div> -->
        <!-- </div> -->
      <!-- </div> -->



{% endblock content %}

plx_scraper/scrape/templates/scrape/list_test.html
{% extends "base.html" %}
{% block content %}
<style>
.search-info{
    font-size: 12px;
    text-align: center;
}
</style>
<br>
<label>Aktualizuj bazę z poniżej podanej lokalizacji</label>
<br>
<label>Wpisz frazę jaką chcesz zaaktualizować</label>
<br>
<form method="POST" action="{% url 'scrape:add_files' %}" class="form-inline">
    {% csrf_token %}
    <input class="form-control mr-sm-2" name="choice" type="text" minlength="4" required>
    <button class="btn btn-outline-success my-2 my-sm-0" value="Search" type="submit" onclick="return confirm('Are you sure？')">Aktualizuj bazę danych</button>
</form>
<a id="confirm_button" href="{% url 'scrape:add_all_files' %}" class="btn-lg btn-danger mt-100 float-right" onclick="return confirm('Are you sure？')">Aktualizuj całą bazę danych</a>
<br>
<label>Aktualna lokaliacja pobierania danych</label>
<input class="form-control" value="{{path}}" type="text" placeholder="{{path}}" disabled>
<br>
<a href="{% url 'scrape:change_path' path.id %}" onclick="return confirm('Are you sure?')" class="btn btn-primary btn-l">Zmień lokalizację</a>
<br>
<p class="search-info">Aby przeszukać pomiędzy wyrazami użyj <b style="font-size:20px;">%</b> </p>

<form method="GET" action="" class="form-inline d-flex justify-content-center">
    <input class="form-control mr-sm-2" name="q" type="text" placeholder="Search" value="{% if request.GET.q %}{{ query }}{% endif %}" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" value="Search" type="submit">Search</button>
</form> 

<label for="">Wszystkie pliki w bazie: <b>{{ count_files }}</b></label>
<br>
<table class="table table-sm table-light">
    <thead>
        <tr>
            <th scope="col">PLX</th>
            <th scope="col">PLX_FGK</th>
            <th scope="col">FILE_NAME</th>
            <th scope="col">N</th>
            <th scope="col">1</th>
            <th scope="col">Copy</th>
        </tr>
        </thead>
        <tbody>
        {% for file in files %}
        <tr>
            <td scope="row">PLX</td>
            <td scope="row">PLX_FGK</td>
            <td id="myInput">{{file.file_name}}</td>
            <td>N</td>
            <td>1</td>
            <td><button class="btn btn-secondary copy-btn">Copy</button></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

plx_scraper/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- For datepicker and timepicker -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />

    <!-- AJAX -->
    <!-- JQuery CDN -->
    <script src="{% static 'javascript/jquery-3.4.1.min.js' %}"></script>

    <!-- FontAwesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <link href='{% static "main.css" %}' rel="stylesheet" media="screen">
    <title>PLX - POLIPOL</title>

</head>
<body>
    {% include "header.html" %}
    <div class="container">
        <br>
        {% if messages %}
                {% for message in messages %}
                    <div id="message" {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
                {% endfor %}
        {% endif %}
        {% block content %}

        {% endblock content %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <!-- JS for copy button and AJAX search -->
    <script type="text/javascript" src='{% static "javascript/main.js" %}'></script>
    <script type="text/javascript" src='{% static "javascript/copy.js" %}'></script>
    <script>
    $(function() {
        setTimeout(function() { $("#message").fadeOut(1500); }, 4000)
    })
    </script>
</body>
</html>

plx_scraper/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/"><b>LOGO</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'scrape:scrape' %}">PLX</a>
      </li>
    </ul>
  </div>
</nav>

scrape/templates/scrape/change_path.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <br>
            {{ form|crispy }}
        <input class="btn-lg btn-success" type="submit" name="submit">
    </form>
{% endblock content %}

scrape/templates/scrape/list.html
{% extends "base.html" %}
{% block content %}
<style>
a.disabled {
  pointer-events: none;
  cursor: default;
}
.search-info{
    font-size: 12px;
    text-align: center;
}
</style>
<div style="display:none;" class="show-hide">
    <div class="d-flex justify-content-between">
        <div class="alert alert-success mr-1 mb-0" role="alert">
          Aktualizuj bazę z poniżej podanej lokalizacji<br>
          Poniżej wpisz frazę jaką chcesz zaaktualizować
        </div>
        <div class="alert alert-info pt-3" role="alert">
          Wszystkie pliki w bazie: <b>{{ count_files }}</b>
        </div>
    </div>
    <div class="d-flex justify-content-between">
        <form method="POST" action="{% url 'scrape:add_files' %}" class="form-inline">
            {% csrf_token %}
            <input class="form-control mr-sm-2" name="choice" type="text" minlength="4" required>
            <button class="btn btn-outline-success my-1 my-sm-0" value="Search" type="submit" onclick="return confirm('Are you sure？')">Aktualizuj bazę danych</button>
        </form>
        <a id="confirm_button" href="{% url 'scrape:add_all_files' %}" class="btn-lg btn-danger {% if not user.is_authenticated %} disabled {% endif %}" onclick="return confirm('Are you sure？')">Aktualizuj całą bazę danych</a>
    </div>

    <label class="mt-2 mb-0">Aktualna lokaliacja pobierania danych</label>
    <input class="form-control m-0" value="{{path}}" type="text" placeholder="{{path}}" disabled>
    <a href="{% url 'scrape:change_path' path.id %}" onclick="return confirm('Are you sure?')" class="btn btn-primary mt-2 btn-l {% if not user.is_authenticated %} disabled {% endif %}">Zmień lokalizację</a>
    <br><button class="btn btn-warning float-right" id="hide">Ukryj panel</button>
</div>
<button class="btn btn-primary btn-lg float-right" id="show">Pokaż panel</button>
<p class="search-info m-0">Użyj znaku<b style="font-size:20px;"> %</b>, aby szukać między wyrazem</p>
<form class="form-inline justify-content-center">
    <i id="search-icon" class="fas fa-search" aria-hidden="true"></i>
    <input id="user-input" class="form-control form-control-lg ml-3 w-50" type="text" placeholder="Szukaj" aria-label="Search">
</form>
<br>

<div id="replaceable-content" class="col-12 m-0">
    {% include 'scrape/results-partial.html' %}
</div>


<script>
$(document).ready(function(){
    $("#hide").click(function(){
        $(".show-hide").hide(300);
        $("#show").show();
    });
  
    $("#show").click(function(){
        $(".show-hide").show(300);
        $("#show").hide();
    });
});

</script>
{% endblock content %}

scrape/templates/scrape/list_without_ajax.html
{% extends "base.html" %}
{% block content %}
<style>
.search-info{
    font-size: 12px;
    text-align: center;
}
</style>
<br>
<label>Aktualizuj bazę z poniżej podanej lokalizacji</label>
<br>
<label>Wpisz frazę jaką chcesz zaaktualizować</label>
<br>
<form method="POST" action="{% url 'scrape:add_files' %}" class="form-inline">
    {% csrf_token %}
    <input class="form-control mr-sm-2" name="choice" type="text" minlength="4" required>
    <button class="btn btn-outline-success my-2 my-sm-0" value="Search" type="submit" onclick="return confirm('Are you sure？')">Aktualizuj bazę danych</button>
</form>
<a id="confirm_button" href="{% url 'scrape:add_all_files' %}" class="btn-lg btn-danger mt-100 float-right" onclick="return confirm('Are you sure？')">Aktualizuj całą bazę danych</a>
<br>
<label>Aktualna lokaliacja pobierania danych</label>
<input class="form-control" value="{{path}}" type="text" placeholder="{{path}}" disabled>
<br>
<a href="{% url 'scrape:change_path' path.id %}" onclick="return confirm('Are you sure?')" class="btn btn-primary btn-l">Zmień lokalizację</a>
<br>
<p class="search-info">Aby przeszukać pomiędzy wyrazami użyj <b style="font-size:20px;">%</b> </p>

<form method="GET" action="" class="form-inline d-flex justify-content-center">
    <input class="form-control mr-sm-2" name="q" type="text" placeholder="Search" value="{% if request.GET.q %}{{ query }}{% endif %}" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" value="Search" type="submit">Search</button>
</form> 

<label for="">Wszystkie pliki w bazie: <b>{{ count_files }}</b></label>
<br>
<table class="table table-sm table-light">
    <thead>
        <tr>
            <th scope="col">PLX</th>
            <th scope="col">PLX_FGK</th>
            <th scope="col">FILE_NAME</th>
            <th scope="col">N</th>
            <th scope="col">1</th>
            <th scope="col">Copy</th>
        </tr>
        </thead>
        <tbody>
        {% for file in files %}
        <tr>
            <td scope="row">PLX</td>
            <td scope="row">PLX_FGK</td>
            <td id="myInput">{{file.file_name}}</td>
            <td>N</td>
            <td>1</td>
            <td><button class="btn btn-secondary copy-btn">Copy</button></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

scrape/templates/scrape/results-partial.html
{% load static %}

{% if files %}
<p class="float-left mb-1">Licznik wyszukanych elementów: <span class="badge badge-warning"><b>{{ files.count }}</b></span></p>
<p class="search-info float-right mb-1">Po wpisaniu frazy tabela wyświetla maksymalnie <b style="font-size:18px;">80</b> rekordów</p>
<div class="table-responsive">
<table class="table table-hover table-sm table-bordered w-100">
    <thead class="thead-dark">
        <tr>
            <th scope="col">PLX</th>
            <th scope="col">PLX_FGK</th>
            <th scope="col">FILE_NAME</th>
            <th scope="col">N</th>
            <th scope="col">1</th>
            <th scope="col" class="text-center">Kopiuj</th>
        </tr>
        </thead>
        <tbody>
        {% for file in files %}
        <tr>
            <td scope="row">{{file.column_one}}</td>
            <td scope="row">{{file.column_two}}</td>
            <td id="myInput">{{file.file_name}}</td>
            <td>{{file.column_three}}</td>
            <td>{{file.column_four}}</td>
            <td class="text-center"><button class="btn btn-outline-secondary btn-block copy-btn">Kopiuj</button></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% else %}
    <br>
    <h3 class="text-center">Brak plików w bazie o takiej nazwie</h3>
{% endif %}

<script type="text/javascript" src='{% static "javascript/copy.js" %}'></script>